name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Tjek repoet ud
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Debug SSH Key
    - name: Debug SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -lf ~/.ssh/id_rsa || echo "Key is invalid or unreadable"

    # 3. Test SSH-forbindelsen manuelt
    - name: Test SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@52.169.156.62 "echo 'SSH Connection Successful'"

    # 4. Deploy manuelt
    - name: Deploy Application
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa azureuser@52.169.156.62 << 'EOF'
          cd ~/dockerPractise
          git pull
          sudo docker stop spring-boot-container || true
          sudo docker rm spring-boot-container || true
          sudo docker build -t spring-boot-app .
          sudo docker run -d \
            --name spring-boot-container \
            -p 8080:8080 \
            --link mysql-container:mysql \
            spring-boot-app
        EOF
